### ISSUE TITLE
melhorar forma de realizar requisição na API na tela de Mapas

### ISSUE THREAD

**Issue by allansrc** [allansrc/valorant_flutter#10]
Na tela de mapas melhorar a forma que está sendo feita a requisição para recuperar a lista de mapas da API.

adicionar a requisição ao load da tela de mapas, ou seja, ao abrir a tela a requisição ser efetuada sem precisar apertar o botão para buscar os mapas.

**Comment by alleffernandes** [comment]
Requisição já melhorada

**Comment by allansrc** [comment]
#15
