### ISSUE TITLE
criar tema para o app

### ISSUE THREAD

**Issue by allansrc** [allansrc/valorant_flutter#14]
Criar um tema de cores padrão do app para as cores pricipais > vermelho.
e secundárias > branco 

como no exemplo.

Não necessáriamente a mesma cor do print. Imagem para ilustração do objetivo

![image](https://user-images.githubusercontent.com/35867294/219450175-fcd697e4-3671-46ae-b58a-2af6c508ff84.png)

**Comment by alleffernandes** [comment]
Done themes

**Comment by allansrc** [comment]
#15
